  
name: rex-contracts

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  run-truffle-tests:

    runs-on: ubuntu-latest
    
    # Run Ganache as service
    services:

      ganache:
        # Ganache Docker Hub image
        image: trufflesuite/ganache-cli:v6.12.2
        ports:
          - 8545:8545
          
    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test:ci

